#!/usr/bin/env node
const childProcess = require('child_process')

try {
  childProcess.execSync('vr --version')
  childProcess.execSync('vr format')
} catch (error) {
  console.log(error.stdout.toString())
  process.exit(1)
}
