#!/usr/bin/env node
const childProcess = require('child_process');

try {
  childProcess.execSync('denon -v');
  // childProcess.execSync('denon lint');
} catch (error) {
  console.log(error.stdout.toString());
  process.exit(1);
}
